name: Deploy main Branch

on:
  push:
    branches:
      - main
      - new-deployment

permissions: {}

jobs:
  build:

    runs-on: ubuntu-latest
    environment:
      name: "production"

    steps:
    - uses: GuillaumeFalourd/clone-github-repo-action@19817562c346ff60f9935158dede6c5ece8fd0ac # v2.3
      with:
        owner: 'deltachat'
        repository: 'invite'
    - run: rm -rf invite/.git
    - name: Upload
      run: |
        mkdir -m 700 -p "$HOME/.ssh"
        echo "${{ secrets.KEY }}" > "$HOME/.ssh/key"
        chmod 600 "$HOME/.ssh/key"
        rsync -rILvh -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" $GITHUB_WORKSPACE/invite/ "${{ secrets.USERNAME }}@i.delta.chat:"
